### ISSUE TITLE
Runtime: nodejs6.10 deprecated

### ISSUE THREAD

**Issue by sgulbetekin** [awslabs/real-time-iot-device-monitoring-with-kinesis#2]
The runtime nodejs6.10 has been deprecated in AWS Lambda, please have a look at the issue here.

**Comment by molinto** [comment]
Agree, the stack does not build because of this.

**Comment by tomnight** [comment]
Thanks for the feedback, we are looking into the issue and will advise.

**Comment by georgebearden** [comment]
This solution was updated to use a more current version of Node.js in the latest commit.
